#include "deadgl.h"
#include <ctype.h>
#include <limits.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>

#define WIRE_EPS 0.025f
static int ok(const DGL_Surface *s){return s&&s->width>0&&s->height>0&&s->pixels&&s->depth;}
static int inb(const DGL_Surface *s,int x,int y){return ok(s)&&x>=0&&y>=0&&x<s->width&&y<s->height;}
static size_t at(const DGL_Surface *s,int x,int y){return (size_t)y*(size_t)s->width+(size_t)x;}
static int mini(int a,int b){return a<b?a:b;} static int maxi(int a,int b){return a>b?a:b;}
static double ed(double ax,double ay,double bx,double by,double px,double py){return (px-ax)*(by-ay)-(py-ay)*(bx-ax);} 
static uint32_t mixc(uint32_t a,uint32_t b,uint32_t c,double wa,double wb,double wc){
    unsigned int ar=(unsigned int)((double)((a>>24)&255u)*wa+(double)((b>>24)&255u)*wb+(double)((c>>24)&255u)*wc+0.5);
    unsigned int rr=(unsigned int)((double)((a>>16)&255u)*wa+(double)((b>>16)&255u)*wb+(double)((c>>16)&255u)*wc+0.5);
    unsigned int gg=(unsigned int)((double)((a>>8)&255u)*wa+(double)((b>>8)&255u)*wb+(double)((c>>8)&255u)*wc+0.5);
    unsigned int bb=(unsigned int)((double)(a&255u)*wa+(double)(b&255u)*wb+(double)(c&255u)*wc+0.5);
    if(ar>255u){ar=255u;} if(rr>255u){rr=255u;} if(gg>255u){gg=255u;} if(bb>255u){bb=255u;} return DGL_ARGB(ar,rr,gg,bb);
}
const char*dgl_version(void){return DGL_VERSION;}
const char*dgl_result_name(int r){switch(r){case DGL_OK:return"DGL_OK";case DGL_ERR_ARG:return"DGL_ERR_ARG";case DGL_ERR_ALLOC:return"DGL_ERR_ALLOC";case DGL_ERR_RANGE:return"DGL_ERR_RANGE";case DGL_ERR_IO:return"DGL_ERR_IO";case DGL_ERR_PARSE:return"DGL_ERR_PARSE";default:return"DGL_ERR_UNKNOWN";}}
int dgl_surface_init(DGL_Surface*s,int w,int h){size_t n; if(!s||w<=0||h<=0||w>DGL_MAX_DIM||h>DGL_MAX_DIM){return DGL_ERR_ARG;} n=(size_t)w*(size_t)h; if(n==0u||n>(size_t)DGL_MAX_PIXELS||n>((size_t)-1/sizeof(uint32_t))||n>((size_t)-1/sizeof(float))){return DGL_ERR_RANGE;} s->pixels=(uint32_t*)calloc(n,sizeof(uint32_t)); s->depth=(float*)malloc(n*sizeof(float)); if(!s->pixels||!s->depth){free(s->pixels);free(s->depth);return DGL_ERR_ALLOC;} s->width=w; s->height=h; dgl_clear_depth(s,DGL_FAR); return DGL_OK;}
void dgl_surface_free(DGL_Surface*s){if(s){free(s->pixels);free(s->depth);s->pixels=NULL;s->depth=NULL;s->width=0;s->height=0;}}
int dgl_surface_valid(const DGL_Surface*s){return ok(s);} size_t dgl_surface_pixel_count(const DGL_Surface*s){return ok(s)?(size_t)s->width*(size_t)s->height:0u;}
void dgl_clear(DGL_Surface*s,uint32_t c){size_t i,n=dgl_surface_pixel_count(s);for(i=0u;i<n;i++){s->pixels[i]=c;}}
void dgl_clear_depth(DGL_Surface*s,float z){size_t i,n;if(!s||!s->depth||s->width<=0||s->height<=0){return;}n=(size_t)s->width*(size_t)s->height;for(i=0u;i<n;i++){s->depth[i]=z;}}
void dgl_pixel(DGL_Surface*s,int x,int y,uint32_t c){if(inb(s,x,y)){s->pixels[at(s,x,y)]=c;}}
uint32_t dgl_get_pixel(const DGL_Surface*s,int x,int y){return inb(s,x,y)?s->pixels[at(s,x,y)]:0u;} float dgl_get_depth(const DGL_Surface*s,int x,int y){return inb(s,x,y)?s->depth[at(s,x,y)]:DGL_FAR;}
void dgl_line(DGL_Surface*s,int x0,int y0,int x1,int y1,uint32_t c){int dx=abs(x1-x0),sx=x0<x1?1:-1,dy=-abs(y1-y0),sy=y0<y1?1:-1,er=dx+dy;if(!ok(s)){return;}for(;;){int e2;dgl_pixel(s,x0,y0,c);if(x0==x1&&y0==y1){break;}e2=er*2;if(e2>=dy){er+=dy;x0+=sx;}if(e2<=dx){er+=dx;y0+=sy;}}}
void dgl_depth_line(DGL_Surface*s,DGL_Vertex a,DGL_Vertex b,uint32_t c){int x0,y0,x1,y1,n,i;if(!ok(s)||!isfinite(a.x)||!isfinite(a.y)||!isfinite(a.z)||!isfinite(b.x)||!isfinite(b.y)||!isfinite(b.z)){return;}x0=(int)lrintf(a.x);y0=(int)lrintf(a.y);x1=(int)lrintf(b.x);y1=(int)lrintf(b.y);n=maxi(abs(x1-x0),abs(y1-y0));if(n>DGL_MAX_DIM*8){return;}for(i=0;i<=n;i++){double t=n==0?0.0:(double)i/(double)n;int x=(int)lrint((double)x0+((double)x1-(double)x0)*t);int y=(int)lrint((double)y0+((double)y1-(double)y0)*t);float z=(float)((double)a.z+((double)b.z-(double)a.z)*t);if(inb(s,x,y)){size_t p=at(s,x,y);if(z<=s->depth[p]+WIRE_EPS){s->depth[p]=z;s->pixels[p]=c;}}}}
void dgl_rect(DGL_Surface*s,int x,int y,int w,int h,uint32_t c){long long x1,y1;if(w<=0||h<=0){return;}x1=(long long)x+(long long)w-1ll;y1=(long long)y+(long long)h-1ll;if(x1<(long long)INT_MIN||x1>(long long)INT_MAX||y1<(long long)INT_MIN||y1>(long long)INT_MAX){return;}dgl_line(s,x,y,(int)x1,y,c);dgl_line(s,x,y,x,(int)y1,c);dgl_line(s,(int)x1,y,(int)x1,(int)y1,c);dgl_line(s,x,(int)y1,(int)x1,(int)y1,c);} 
void dgl_fill_rect(DGL_Surface*s,int x,int y,int w,int h,uint32_t c){int yy,x0=maxi(0,x),y0=maxi(0,y),x1,y1;if(!ok(s)||w<=0||h<=0){return;}x1=mini(s->width,x+w);y1=mini(s->height,y+h);for(yy=y0;yy<y1;yy++){int xx;size_t row=(size_t)yy*(size_t)s->width;for(xx=x0;xx<x1;xx++){s->pixels[row+(size_t)xx]=c;}}}
void dgl_circle(DGL_Surface*s,int cx,int cy,int r,uint32_t c){int x=r,y=0,e=1-x;if(!ok(s)||r<0||r>DGL_MAX_DIM*2){return;}while(x>=y){dgl_pixel(s,cx+x,cy+y,c);dgl_pixel(s,cx+y,cy+x,c);dgl_pixel(s,cx-y,cy+x,c);dgl_pixel(s,cx-x,cy+y,c);dgl_pixel(s,cx-x,cy-y,c);dgl_pixel(s,cx-y,cy-x,c);dgl_pixel(s,cx+y,cy-x,c);dgl_pixel(s,cx+x,cy-y,c);y++;if(e<0){e+=2*y+1;}else{x--;e+=2*(y-x+1);}}}
void dgl_fill_circle(DGL_Surface*s,int cx,int cy,int r,uint32_t c){int y;if(!ok(s)||r<0||r>DGL_MAX_DIM*2){return;}for(y=-r;y<=r;y++){int rr=r*r-y*y;int sp=rr<=0?0:(int)sqrt((double)rr);dgl_line(s,cx-sp,cy+y,cx+sp,cy+y,c);}}
void dgl_wire_tri(DGL_Surface*s,DGL_Vertex a,DGL_Vertex b,DGL_Vertex c,uint32_t col){dgl_line(s,(int)lrintf(a.x),(int)lrintf(a.y),(int)lrintf(b.x),(int)lrintf(b.y),col);dgl_line(s,(int)lrintf(b.x),(int)lrintf(b.y),(int)lrintf(c.x),(int)lrintf(c.y),col);dgl_line(s,(int)lrintf(c.x),(int)lrintf(c.y),(int)lrintf(a.x),(int)lrintf(a.y),col);} 
void dgl_wire_tri_depth(DGL_Surface*s,DGL_Vertex a,DGL_Vertex b,DGL_Vertex c,uint32_t col){dgl_depth_line(s,a,b,col);dgl_depth_line(s,b,c,col);dgl_depth_line(s,c,a,col);} 
void dgl_tri(DGL_Surface*s,DGL_Vertex a,DGL_Vertex b,DGL_Vertex c){double ax,ay,bx,by,cx,cy,ar;int x,y,minx,maxx,miny,maxy;if(!ok(s)||!isfinite(a.x)||!isfinite(a.y)||!isfinite(a.z)||!isfinite(b.x)||!isfinite(b.y)||!isfinite(b.z)||!isfinite(c.x)||!isfinite(c.y)||!isfinite(c.z)){return;}ax=(double)a.x;ay=(double)a.y;bx=(double)b.x;by=(double)b.y;cx=(double)c.x;cy=(double)c.y;ar=ed(ax,ay,bx,by,cx,cy);if(fabs(ar)<1e-9){return;}minx=maxi(0,(int)floor(fmin(ax,fmin(bx,cx))));maxx=mini(s->width-1,(int)ceil(fmax(ax,fmax(bx,cx))));miny=maxi(0,(int)floor(fmin(ay,fmin(by,cy))));maxy=mini(s->height-1,(int)ceil(fmax(ay,fmax(by,cy))));for(y=miny;y<=maxy;y++){for(x=minx;x<=maxx;x++){double px=(double)x+0.5,py=(double)y+0.5,wa=ed(bx,by,cx,cy,px,py)/ar,wb=ed(cx,cy,ax,ay,px,py)/ar,wc=1.0-wa-wb;if(wa>=-1e-9&&wb>=-1e-9&&wc>=-1e-9){float z=(float)(wa*(double)a.z+wb*(double)b.z+wc*(double)c.z);size_t p=at(s,x,y);if(z<s->depth[p]){s->depth[p]=z;s->pixels[p]=mixc(a.color,b.color,c.color,wa,wb,wc);}}}}}
void dgl_quad(DGL_Surface*s,DGL_Vertex a,DGL_Vertex b,DGL_Vertex c,DGL_Vertex d){dgl_tri(s,a,b,c);dgl_tri(s,a,c,d);} void dgl_wire_quad_depth(DGL_Surface*s,DGL_Vertex a,DGL_Vertex b,DGL_Vertex c,DGL_Vertex d,uint32_t col){dgl_depth_line(s,a,b,col);dgl_depth_line(s,b,c,col);dgl_depth_line(s,c,d,col);dgl_depth_line(s,d,a,col);} 
uint64_t dgl_hash(const DGL_Surface*s){uint64_t h=1469598103934665603ull;size_t i,n=dgl_surface_pixel_count(s);if(!ok(s)){return 0u;}h^=(uint64_t)(uint32_t)s->width;h*=1099511628211ull;h^=(uint64_t)(uint32_t)s->height;h*=1099511628211ull;for(i=0u;i<n;i++){uint32_t p=s->pixels[i];h^=(uint64_t)(p&255u);h*=1099511628211ull;h^=(uint64_t)((p>>8)&255u);h*=1099511628211ull;h^=(uint64_t)((p>>16)&255u);h*=1099511628211ull;h^=(uint64_t)((p>>24)&255u);h*=1099511628211ull;}return h;}
int dgl_save_ppm(const DGL_Surface*s,const char*path){FILE*f;int y;if(!ok(s)||!path||path[0]=='\0'){return DGL_ERR_ARG;}f=fopen(path,"wb");if(!f){return DGL_ERR_IO;}if(fprintf(f,"P6\n%d %d\n255\n",s->width,s->height)<0){fclose(f);return DGL_ERR_IO;}for(y=0;y<s->height;y++){int x;for(x=0;x<s->width;x++){uint32_t p=s->pixels[at(s,x,y)];unsigned char rgb[3];rgb[0]=(unsigned char)((p>>16)&255u);rgb[1]=(unsigned char)((p>>8)&255u);rgb[2]=(unsigned char)(p&255u);if(fwrite(rgb,1u,3u,f)!=3u){fclose(f);return DGL_ERR_IO;}}}return fclose(f)==0?DGL_OK:DGL_ERR_IO;}
int dgl_parse_color(const char*t,uint32_t*out){const char*p;uint32_t v=0u;int n=0;if(!t||!out){return DGL_ERR_ARG;}p=t;if(*p=='#'){p++;}else if(p[0]=='0'&&(p[1]=='x'||p[1]=='X')){p+=2;}while(*p!='\0'&&*p!='\n'&&*p!='\r'){int x;if(!isxdigit((unsigned char)*p)){return DGL_ERR_PARSE;}x=isdigit((unsigned char)*p)?*p-'0':10+(tolower((unsigned char)*p)-'a');v=(v<<4)|(uint32_t)x;n++;p++;}if(n==6){*out=0xff000000u|v;return DGL_OK;}if(n==8){*out=v;return DGL_OK;}return DGL_ERR_PARSE;}
